--!strict

const Implementation = require(script.Parent._Index["quenty/avatarcatalogservice@0.0.1"]["AvatarCatalogService"])

export type AvatarScales = Implementation.AvatarScales
export type BodyPartDefinition = Implementation.BodyPartDefinition
export type PackageDefinition = Implementation.PackageDefinition
export type AvatarCatalogService = Implementation.AvatarCatalogService

return Implementation
