return {
	shutdown = {
		complete = {
			subtitle = "Mise à jour terminée...",
			title = "Redémarrage des serveurs pour une mise à jour du jeu.",
		},
		lobby = {
			subtitle = "Téléportation dans un instant...",
			title = "Redémarrage des serveurs pour une mise à jour du jeu.",
		},
		restart = {
			subtitle = "S'il vous plaît, attendez...",
			title = "Redémarrage des serveurs pour une mise à jour du jeu.",
		},
	},
}
