return {
	shutdown = {
		complete = {
			subtitle = "Atualização concluída...",
			title = "Reiniciando servidores para uma atualização do jogo.",
		},
		lobby = {
			subtitle = "Teleportando de volta em um momento...",
			title = "Reiniciando servidores para uma atualização do jogo.",
		},
		restart = {
			subtitle = "Por favor, aguarde...",
			title = "Reiniciando servidores para uma atualização do jogo.",
		},
	},
}
