--!strict

const Implementation = require(script.Parent._Index["quenty/avatareditorutils@0.0.1"]["AvatarEditorUtils"])

export type AvatarItemBundledItemDetails = Implementation.AvatarItemBundledItemDetails
export type PremiumPricingItemDetails = Implementation.PremiumPricingItemDetails
export type AvatarItemDetails = Implementation.AvatarItemDetails
export type AvatarRulesWearableAssetType = Implementation.AvatarRulesWearableAssetType
export type AvatarRulesBodyColor = Implementation.AvatarRulesBodyColor
export type AvatarRuleDefaultClothingAssetLists = Implementation.AvatarRuleDefaultClothingAssetLists
export type AvatarRules = Implementation.AvatarRules

return Implementation
