--!strict

const Implementation = require(script.Parent._Index["quenty/brine@0.0.1"]["BrineTypes"])

export type Brined = Implementation.Brined
export type Intermediate = Implementation.Intermediate
export type BrineProperties = Implementation.BrineProperties
export type BrineAttributes = Implementation.BrineAttributes
export type BrineTags = Implementation.BrineTags
export type BrineInstance = Implementation.BrineInstance
export type ExtraData = Implementation.ExtraData
export type BrineInstanceWithExtraData = Implementation.BrineInstanceWithExtraData
export type InstanceHook = Implementation.InstanceHook
export type References = Implementation.References
export type SharedOptons = Implementation.SharedOptons
export type SerializeBrineOptions = Implementation.SerializeBrineOptions
export type DeserializeBrineOptions = Implementation.DeserializeBrineOptions
export type SafeOptions = Implementation.SafeOptions
export type BrineOptions = Implementation.BrineOptions
export type SafeBrineOptions = Implementation.SafeBrineOptions

return Implementation
