--!strict

const Implementation = require(script.Parent._Index["quenty/cooldownservice@0.0.1"]["Shared"]["CooldownServiceTypes"])

export type Clock = Implementation.Clock
export type CooldownType = Implementation.CooldownType
export type DefaultCooldownValue = Implementation.DefaultCooldownValue
export type BurstCooldownValue = Implementation.BurstCooldownValue
export type CooldownValue = Implementation.CooldownValue
export type CooldownState = Implementation.CooldownState
export type CooldownModel = Implementation.CooldownModel
export type HeapEntry<T> = Implementation.HeapEntry<T>

return Implementation
