--!strict

const Implementation = require(script.Parent._Index["quenty/marketplaceutils@0.0.1"]["MarketplaceUtils"])

export type CreatorProductInfo = Implementation.CreatorProductInfo
export type AssetProductInfo = Implementation.AssetProductInfo
export type GamePassOrDeveloperProductInfo = Implementation.GamePassOrDeveloperProductInfo
export type SubscriptionProductInfo = Implementation.SubscriptionProductInfo
export type UserSubscriptonStatus = Implementation.UserSubscriptonStatus

return Implementation
