--!strict

const Implementation = require(script.Parent._Index["quenty/tie@0.0.1"]["Shared"]["TieDefinition"])

export type TieRealm = Implementation.TieRealm
export type TieDefinitionType = Implementation.TieDefinitionType
export type TieDefinitionTypes = Implementation.TieDefinitionTypes
export type TieDefinition<T> = Implementation.TieDefinition<T>
export type TieMemberMap = Implementation.TieMemberMap

return Implementation
