--!strict

const Implementation = require(script.Parent._Index["quenty/webhook@0.0.1"]["WebhookTypes"])

export type EmbedField = Implementation.EmbedField
export type EmbedFooter = Implementation.EmbedFooter
export type EmbedImage = Implementation.EmbedImage
export type EmbedThumbnail = Implementation.EmbedThumbnail
export type EmbedAuthor = Implementation.EmbedAuthor
export type Embed = Implementation.Embed
export type MessageOptions = Implementation.MessageOptions
export type WebhookClientOptions = Implementation.WebhookClientOptions
export type WebhookResponse = Implementation.WebhookResponse

return Implementation
