return {
	shutdown = {
		complete = {
			subtitle = "Update abgeschlossen...",
			title = "Server werden für ein Spielupdate neu gestartet.",
		},
		lobby = {
			subtitle = "Ich teleportiere mich gleich zurück ...",
			title = "Server werden für ein Spielupdate neu gestartet.",
		},
		restart = {
			subtitle = "Bitte warten...",
			title = "Server werden für ein Spielupdate neu gestartet.",
		},
	},
}
