return {
	shutdown = {
		complete = {
			subtitle = "Actualización completa...",
			title = "Reiniciando servidores para una actualización del juego.",
		},
		lobby = {
			subtitle = "Teletransportándome de regreso en un momento...",
			title = "Reiniciando servidores para una actualización del juego.",
		},
		restart = {
			subtitle = "Espere por favor...",
			title = "Reiniciando servidores para una actualización del juego.",
		},
	},
}
