return {
	shutdown = {
		complete = {
			subtitle = "Aggiornamento completato...",
			title = "Riavvio dei server per un aggiornamento del gioco.",
		},
		lobby = {
			subtitle = "Mi teletrasporto indietro tra un attimo...",
			title = "Riavvio dei server per un aggiornamento del gioco.",
		},
		restart = {
			subtitle = "Attendere prego...",
			title = "Riavvio dei server per un aggiornamento del gioco.",
		},
	},
}
