return {
	shutdown = {
		complete = {
			subtitle = "Aktualizacja zakończona...",
			title = "Ponowne uruchamianie serwerów w celu aktualizacji gry.",
		},
		lobby = {
			subtitle = "Za chwilę teleportuję się z powrotem...",
			title = "Ponowne uruchamianie serwerów w celu aktualizacji gry.",
		},
		restart = {
			subtitle = "Proszę czekać...",
			title = "Ponowne uruchamianie serwerów w celu aktualizacji gry.",
		},
	},
}
