return {
	shutdown = {
		complete = {
			subtitle = "Güncelleme tamamlandı...",
			title = "Bir oyun güncellemesiiçin sunucular yeniden başlatılıyor.",
		},
		lobby = {
			subtitle = "Birazdan geriışınlanıyorum...",
			title = "Bir oyun güncellemesiiçin sunucular yeniden başlatılıyor.",
		},
		restart = {
			subtitle = "Lütfen bekleyin...",
			title = "Bir oyun güncellemesiiçin sunucular yeniden başlatılıyor.",
		},
	},
}
